### ISSUE TITLE
Any instruction using your code?

### ISSUE THREAD

**Issue by randomwangran** [mohuangrui/ArtraCFD#1]
For example, I have a *.msh (or *.stl) file that describe a circular cylinder and computational domain.

To simulate this circular cylinder at a Reynolds number 5e5 without considering compressible effect how should I do?

Do you have any script to achieve this?

I would like to contribute my effort to this CFD code.

**Comment by randomwangran** [comment]
It seems that the creator is too busy to make people running this cfd code.

**Comment by mohuangrui** [comment]
This is a C program, and you can run it like any other C program. Anyway, I have just added the basic steps to compile and run the code in the ReadMe, in case you are not familiar with running a C program.

However, for any other properties and features of the code, you have to read the algorithms and equations. Sorry that I'm not available to write a comprehensive code documentation.

**Comment by randomwangran** [comment]
Thanks, the instruction is very helpful. I will try it later on.

https://github.com/mohuangrui/ArtraCFD/commit/aec0367697b29fb13320576f811acbbcf3d54272
